import React from 'react';
import styles from './Main.module.css'

function Main() {
  return (
    <main>
      <h2>Random Images</h2>
      <div className={styles.card_container}>
        <div className={styles.card}>
          <div className={styles.square}>
            <img src="https://picsum.photos/200/200" alt="random image generated by https://picsum.photos/"/>
          </div>
          <p>This is some subtext showing a random image</p>
        </div>

        <div className={styles.card}>
          <div className={styles.square}>
            <img src="https://picsum.photos/200/200" alt="random image generated by https://picsum.photos/"/>
          </div>
          <p>This is some subtext showing a random image</p>
        </div>

        <div className={styles.card}>
          <div className={styles.square}>
            <img src="https://picsum.photos/200/200" alt="random image generated by https://picsum.photos/"/>
          </div>
          <p>This is some subtext showing a random image</p>
        </div>

        <div className={styles.card}>
          <div className={styles.square}>
            <img src="https://picsum.photos/200/200" alt="random image generated by https://picsum.photos/"/>
          </div>
          <p>This is some subtext showing a random image</p>
        </div>
      </div>
    </main>
  );
}

export default Main;